export enum testType {
  ACCEPTANCE = 1,
  ACCESSABILITY = 2,
  AUTOMATED = 3,
  COMPATIBILITY = 4,
  DESTRUCTIVE = 5,
  FUNCTIONAL = 6,
  OTHER = 7,
  PERFORMANCE = 8,
  REGRESSION = 9,
  SECURITY = 10,
  SMOKE_AND_SANITY = 11,
  USABILITY = 12,
}
